public class XeroCurrWrapper {

    // public class Currencies {
    //     public String Code;
    //     public String Description;
    // }

    // public String Id;
    // public String Status;
    // public String ProviderName;
    // public String DateTimeUTC;
    // public List<Currencies> Currencies;

    
    // public static XeroCurrWrapper parse(String json) {
    //     return (XeroCurrWrapper) System.JSON.deserialize(json, XeroCurrWrapper.class);
    // }
}